// Generated by CoffeeScript 1.12.5
(function() {
  var fs, page, path, system, testfile;

  system = require('system');

  fs = require('fs');

  path = require('path');

  page = require('webpage').create();

  page.settings.userAgent = 'phantom';

  page.viewportSize = {
    width: 900,
    height: 600
  };

  page.onConsoleMessage = function(msg) {
    return console.log(msg);
  };

  page.onError = function(msg, trace) {
    console.log(msg);
    return trace.forEach(function(item) {
      return console.log('  ', item.file, ':', item.line);
    });
  };

  page.onResourceError = function(resourceError) {
    return console.log(resourceError.errorString);
  };

  testfile = path.join(path.dirname(system.args[0]), 'dom_tests.html');

  page.open(testfile, function(status) {
    var runTests;
    if (status !== 'success') {
      console.log('Unable to load tests.');
      phantom.exit(1);
    }
    runTests = function() {
      var data, testsFailed;
      testsFailed = page.evaluate(function() {
        Tests.run();
        return Tests.testsFailed;
      });
      if (system.args[1] === '--coverage') {
        data = page.evaluate(function() {
          return JSON.stringify(_$jscoverage);
        });
        fs.write(dirname + 'dom_tests_coverage.json', data, 'w');
      }
      if (testsFailed > 0) {
        return phantom.exit(1);
      } else {
        return phantom.exit(0);
      }
    };
    return setTimeout(runTests, 10);
  });

}).call(this);
