// Generated by CoffeeScript 1.12.5
(function() {
  var slice = [].slice;

  Tests.outputMethod = function() {
    var args, newOutput;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    newOutput = args.join("\n");
    newOutput = newOutput.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    newOutput = newOutput.replace(/\/([^:\/]+):([0-9]+):([0-9]+)/, "/<span class='errorPosition'>$1:$2</span>:$3");
    document.getElementById("output-div").innerHTML += "<div class='output-section'>" + newOutput + "</div>";
    return console.log.apply(console, args);
  };

  if (navigator.userAgent !== 'phantom') {
    document.addEventListener("DOMContentLoaded", function() {
      return setTimeout(Tests.run, 200);
    });
  }

}).call(this);
