// Generated by CoffeeScript 1.12.5
(function() {
  var hasProp = {}.hasOwnProperty;

  require("../shoulda.js/shoulda.js");

  global.extend = function(hash1, hash2) {
    var key;
    for (key in hash2) {
      if (!hasProp.call(hash2, key)) continue;
      hash1[key] = hash2[key];
    }
    return hash1;
  };

}).call(this);
